export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const GET_FILTERED_PRODUCTS_LOADING = "GET_FILTERED_PRODUCTS_LOADING";
export const GET_FILTERED_PRODUCTS_SUCCESS = "GET_FILTERED_PRODUCTS_SUCCESS";
export const GET_FILTERED_PRODUCTS_ERROR = "GET_FILTERED_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT_LOADING = "GET_SINGLE_PRODUCT_LOADING";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR  ";

export const GET_SLIDER_PRODUCT_LOADING = "GET_SLIDER_PRODUCT_LOADING";
export const GET_SLIDER_PRODUCT_SUCCESS = "GET_SLIDER_PRODUCT_SUCCESS";
export const GET_SLIDER_PRODUCT_ERROR = "GET_SLIDER_PRODUCT_ERROR  ";
