export const GET_OTP = "GET_OTP";
export const GET_LOGIN = "GET_LOGIN";
export const LOGOUT = "LOGOUT";

// LOGIN
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

// USER_SIGNUP
export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

// USER_LOGOUT
export const USER_LOGOUT_LOADING = "USER_LOGOUT_LOADING";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

// USER_GET_PROFILE
export const USER_GET_PROFILE_LOADING = "USER_GET_PROFILE_LOADING";
export const USER_GET_PROFILE_SUCCESS = "USER_GET_PROFILE_SUCCESS";
export const USER_GET_PROFILE_ERROR = "USER_GET_PROFILE_ERROR";

export const USER_REQUIRE_AUTH = "USER_REQUIRE_AUTH";
